# Generated by Django 3.2.4 on 2021-06-28 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0003_staffregistration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='contact',
            field=models.BigIntegerField(),
        ),
    ]
