# Generated by Django 3.2.4 on 2021-07-03 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0006_studentregistration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addclass',
            name='class_teacher',
        ),
    ]
