# Generated by Django 3.2.4 on 2021-07-03 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0007_remove_addclass_class_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classes', models.CharField(max_length=50)),
            ],
        ),
    ]
