# Generated by Django 3.2.4 on 2021-07-03 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0009_subjects'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subjects',
            old_name='Subject',
            new_name='subject',
        ),
    ]
