# Generated by Django 3.2.4 on 2021-07-04 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0011_delete_addclass'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddClasses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classes', models.CharField(max_length=50)),
            ],
        ),
    ]
