# Generated by Django 3.2.4 on 2021-07-04 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0012_addclasses'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AddClasses',
            new_name='AddedClasses',
        ),
    ]
