# Generated by Django 3.2.4 on 2021-07-12 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0015_rejectedstaff'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('place', models.CharField(max_length=50)),
                ('pic', models.CharField(max_length=50)),
            ],
        ),
    ]
