# Generated by Django 3.2.4 on 2021-07-26 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0017_delete_staffregistration'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default=None, max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.CharField(default=None, max_length=50)),
                ('contact', models.BigIntegerField(default=None)),
                ('address', models.CharField(max_length=500)),
                ('dob', models.DateField()),
                ('user_name', models.CharField(max_length=50)),
                ('password', models.CharField(default=None, max_length=50)),
                ('profile_pic', models.CharField(max_length=50)),
            ],
        ),
    ]
