# Generated by Django 3.2.4 on 2021-07-26 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0018_staffregistration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StaffRegistration',
        ),
    ]
