# Generated by Django 3.2.4 on 2021-08-03 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0020_staffregistration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentRegistration',
        ),
        migrations.AlterField(
            model_name='staffregistration',
            name='profile_pic',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
