# Generated by Django 3.2.4 on 2021-08-16 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0024_tempstaff'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TempStaff',
            new_name='Staff',
        ),
    ]
