# Generated by Django 3.2.4 on 2021-08-16 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0026_regectedstaff'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RegectedStaff',
        ),
        migrations.DeleteModel(
            name='RejectedStaff',
        ),
    ]
