# Generated by Django 3.2.4 on 2021-08-23 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0032_learnaj'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LearnAj',
        ),
    ]
