# Generated by Django 3.2.4 on 2021-08-29 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0034_adminlogindata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AddedSubjects',
        ),
    ]
