# Generated by Django 3.2.4 on 2021-08-29 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0036_addedsubjects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addedsubjects',
            name='teacher',
        ),
    ]
