# Generated by Django 3.2.4 on 2021-09-10 04:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0042_chapter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_name', models.CharField(default=None, max_length=50)),
                ('topic_file', models.CharField(blank=True, max_length=50)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_app.chapter')),
                ('classes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_app.addedclasses')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_app.addedsubjects')),
            ],
        ),
    ]
