# Generated by Django 3.2.4 on 2021-10-02 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0045_staffregistration_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StaffRegistration',
            new_name='Staff123',
        ),
    ]
