# Generated by Django 3.2.4 on 2021-10-02 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0046_rename_staffregistration_staff123'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RegectedStaff',
        ),
        migrations.DeleteModel(
            name='Staff123',
        ),
    ]
