# Generated by Django 3.2.4 on 2021-10-02 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0047_auto_20211002_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentregistration',
            name='status',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
