# Generated by Django 3.2.4 on 2021-10-02 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0048_studentregistration_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Students123',
            fields=[
                ('registration_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(default=None, max_length=50)),
                ('last_name', models.CharField(default=None, max_length=50)),
                ('classes', models.CharField(default=None, max_length=50)),
                ('contact', models.BigIntegerField(default=None)),
                ('address', models.CharField(default=None, max_length=500)),
                ('dob', models.DateField(default=None)),
                ('user_name', models.CharField(default=None, max_length=50)),
                ('password', models.CharField(default=None, max_length=50)),
                ('profile_pic', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='StudentRegistration',
        ),
        migrations.AddField(
            model_name='students',
            name='status',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
