# Generated by Django 3.2.4 on 2021-10-02 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0049_auto_20211002_1951'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeclinedStudentDetails',
        ),
        migrations.DeleteModel(
            name='Registration',
        ),
        migrations.DeleteModel(
            name='Students123',
        ),
    ]
